receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    endpoint: "jaeger:16686"
    tls:
      insecure: true

  logging:
    verbosity: detailed
  elasticsearch/log:
    endpoints: [https://es01:9200]
    user: elastic
    password: changeme
    logs_index: my_log_index
    tls:
      insecure_skip_verify: true

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [ 5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1000ms ]

processors:
  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: loki.resource.labels
        value: service_name

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp, spanmetrics ]
    metrics:
      receivers: [ spanmetrics ]
      exporters: [ prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ resource ]
      exporters: [ elasticsearch/log ]
